### ISSUE TITLE
Windows "No such file or directory"

### ISSUE THREAD

**Issue by kool601** [windytan/ctape#5]
I'm on windows 7, and when I use the tape-write.rb, it gives me this error:

tape-write.rb:13:in `popen': No such file or directory - sox -q -t .raw -r 44100
 -c 1 -b 16 -e signed-integer - -t alsa "default" (Errno::ENOENT)
        from tape-write.rb:13:in`<main>'

What's going on?

**Comment by windytan** [comment]
You need to have SoX installed and added to your path: https://github.com/JoFrhwld/FAVE/wiki/Sox-on-Windows

Also, you're using the ALSA (Linux audio) backend which is not available on Windows. I'm not sure exactly how to use the Windows audio device on SoX, unfortunately.

**Comment by kool601** [comment]
Man, I wish I knew the backend for windows.

**Comment by kool601** [comment]
It's giving me this error:

C:\Users\Justin\Downloads\ctape-master\ctape-master>tape-write.rb test.txt
sox FAIL formats: no handler for given file type `sndfile'
C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:34:in `write':
 Broken pipe (Errno::EPIPE)
        from C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:3
4:in `block (2 levels) in <main>'
        from C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:3
4:in `times'
        from C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:3
4:in `block in <main>'
        from C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:3
2:in `times'
        from C:/Users/Justin/Downloads/ctape-master/ctape-master/tape-write.rb:3
2:in `<main>'


Which I found out that Windows backend might be "sndfile".

**Comment by kool601** [comment]
What does that error mean? "Broken pipe"?

**Comment by windytan** [comment]
SoX pipe was closed abruptly.
