### ISSUE TITLE
No No such file or directory

### ISSUE THREAD

**Issue by bismilla45** [windytan/ctape#6]
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]

C:\Users\Jc>C:\Users\Jc\Desktop\tape-write.rb < C:\Users\Jc\Desktop\asd.wma
C:/Users/Jc/Desktop/tape-write.rb:8:in `initialize': No such file or directory @
 rb_sysopen - config.yml (Errno::ENOENT)
        from C:/Users/Jc/Desktop/tape-write.rb:8:in`open'
        from C:/Users/Jc/Desktop/tape-write.rb:8:in `<main>'
This is the error,i dont know whats happend.I have SoX

**Comment by windytan** [comment]
Hi, you need to have config.yml in the same directory you run the script in.

**Comment by bismilla45** [comment]
i corrected it but i have the same error and this added: 
C:\Users\Jc>C:\Users\Jc\Desktop\ctape-master\tape-read.rb < C:\Users\Jc\Desktop\
52663493-256-k675616.jpg
C:/Users/Jc/Desktop/ctape-master/tape-read.rb:8:in `initialize': No such file or
 directory @ rb_sysopen - config.yml (Errno::ENOENT)
        from C:/Users/Jc/Desktop/ctape-master/tape-read.rb:8:in `open'
        from C:/Users/Jc/Desktop/ctape-master/tape-read.rb:8:in `<main>'

C:\Users\Jc>

**Comment by windytan** [comment]
Try running it from the ctape-master directory. This means you need to 'cd' into that directory first. That's pretty much all I can say, I don't have Windows myself.
